#!/bin/bash

MAN="$HOME/tmp/man-pages-2.27"
MAN2="$MAN/man2"
MAN3="$MAN/man3"
ERR_FUNC="$PWD/scripts/err_func"

if [ ! -d $MAN ]; then
	echo "error: Mandir '$MAN' does not exist."
	exit 1
fi

if [ ! -d $MAN2 ]; then
	echo "error: Mandir(2) '$MAN2' does not exist."
	exit 1
fi

if [ ! -d $MAN3 ]; then
	echo "error: Mandir(3) '$MAN3' does not exist."
	exit 1
fi

if [ ! -f $ERR_FUNC ]; then
	echo "error: Err_func '$ERR_FUNC' does not exist."
	exit 1
fi

cat $PWD/src/error.c.template.c || exit 1

$ERR_FUNC $MAN2/accept.2 || exit 1
$ERR_FUNC $MAN2/bind.2 || exit 1
$ERR_FUNC $MAN2/chdir.2 || exit 1
$ERR_FUNC $MAN2/chmod.2 || exit 1
$ERR_FUNC $MAN2/close.2 || exit 1
$ERR_FUNC $MAN2/connect.2 || exit 1
$ERR_FUNC $MAN2/dup2.2 || exit 1
$ERR_FUNC $MAN2/execve.2 || exit 1
$ERR_FUNC $MAN2/fork.2 || exit 1
$ERR_FUNC $MAN2/fstat.2 || exit 1
$ERR_FUNC $MAN2/gethostname.2 || exit 1
$ERR_FUNC $MAN2/getsockname.2 || exit 1
$ERR_FUNC $MAN2/kill.2 || exit 1
$ERR_FUNC $MAN2/listen.2 || exit 1
$ERR_FUNC $MAN2/lstat.2 || exit 1
$ERR_FUNC $MAN2/mmap.2 || exit 1
$ERR_FUNC $MAN2/open.2 || exit 1
$ERR_FUNC $MAN2/pipe.2 || exit 1
$ERR_FUNC $MAN2/read.2 || exit 1
$ERR_FUNC $MAN2/recvfrom.2 || exit 1
$ERR_FUNC $MAN2/recvmsg.2 || exit 1
$ERR_FUNC $MAN2/sendmsg.2 || exit 1
$ERR_FUNC $MAN2/sendto.2 || exit 1
$ERR_FUNC $MAN2/shmat.2 || exit 1
$ERR_FUNC $MAN2/shmctl.2 || exit 1
$ERR_FUNC $MAN2/shmdt.2 || exit 1
$ERR_FUNC $MAN2/shmget.2 || exit 1
$ERR_FUNC $MAN2/sigaction.2 || exit 1
$ERR_FUNC $MAN2/sigprocmask.2 || exit 1
$ERR_FUNC $MAN2/socket.2 || exit 1
$ERR_FUNC $MAN2/stat.2 || exit 1
$ERR_FUNC $MAN2/wait.2 || exit 1
$ERR_FUNC $MAN2/write.2 || exit 1

$ERR_FUNC $MAN3/fopen.3 || exit 1
$ERR_FUNC $MAN3/freopen.3 || exit 1
$ERR_FUNC $MAN3/getaddrinfo.3 || exit 1
$ERR_FUNC $MAN3/inet_ntop.3 || exit 1
$ERR_FUNC $MAN3/inet_pton.3 || exit 1
$ERR_FUNC $MAN3/malloc.3 || exit 1
$ERR_FUNC $MAN3/opendir.3 || exit 1
$ERR_FUNC $MAN3/sigsetops.3 || exit 1
$ERR_FUNC /usr/share/man/man3p/pthread_attr_setdetachstate.3p || exit 1
$ERR_FUNC /usr/share/man/man3p/pthread_create.3p || exit 1
$ERR_FUNC /usr/share/man/man3p/pthread_sigmask.3p || exit 1
